### ISSUE TITLE
grafana datasource install issue

### ISSUE THREAD

**Issue by alter** [VictoriaMetrics/grafana-datasource#109]
`Error: container's runAsUser breaks non-root policy (pod: "grafana-6c94b9b575-whzqw_grafana(6ffc9589-d533-4064-a8b5-67ac4a6bf0aa)", container: load-vm-ds-plugin)`

I added the following options to my values.yml in grafana's helm chart:
```
        extraInitContainers:
          - name: "load-vm-ds-plugin"
            image: "curlimages/curl:7.85.0"
            command: [ "/bin/sh" ]
            workingDir: "/var/lib/grafana/plugins"
            securityContext:
              runAsUser: 0
            args:
             - "-c"
             - |
               set -ex
               mkdir -p /var/lib/grafana/plugins/
               ver=$(curl -s https://api.github.com/repos/VictoriaMetrics/grafana-datasource/releases/latest | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1)
               curl -L https://github.com/VictoriaMetrics/grafana-datasource/releases/download/$ver/victoriametrics-datasource-$ver.tar.gz -o /var/lib/grafana/plugins/plugin.tar.gz
               tar -xf /var/lib/grafana/plugins/plugin.tar.gz -C /var/lib/grafana/plugins/
               rm /var/lib/grafana/plugins/plugin.tar.gz
               chown -R 472:472 /var/lib/grafana/plugins/
            volumeMounts:
              - name: storage
                mountPath: /var/lib/grafana
```

Grafana chart version: 6.60.4

**Comment by hagen1778** [comment]
@alter could you try updating `securityContext` obejct to the following:
```
 securityContext:
    runAsUser: 472
    fsGroup: 472
```
@zekker6 do you think we should update our recommendations in docs?

**Comment by zekker6** [comment]
@alter Please, check out this configuration:
```
    extraInitContainers:
      - name: "load-vm-ds-plugin"
        image: "curlimages/curl:7.85.0"
        command: [ "/bin/sh" ]
        workingDir: "/var/lib/grafana"
        securityContext:
          runAsUser: 472
          runAsNonRoot: true
          runAsGroup: 472
        args:
          - "-c"
          - |
            set -ex
            mkdir -p /var/lib/grafana/plugins/
            ver=$(curl -s https://api.github.com/repos/VictoriaMetrics/grafana-datasource/releases/latest | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1)
            curl -L https://github.com/VictoriaMetrics/grafana-datasource/releases/download/$ver/victoriametrics-datasource-$ver.tar.gz -o /var/lib/grafana/plugins/plugin.tar.gz
            tar -xf /var/lib/grafana/plugins/plugin.tar.gz -C /var/lib/grafana/plugins/
            rm /var/lib/grafana/plugins/plugin.tar.gz
        volumeMounts:
          - name: storage
            mountPath: /var/lib/grafana
```
Note that `securityContext` was updated(as @hagen1778 pointed out) and also `workDir` have been adjusted.

fyi: @hagen1778 I'll update readme to include an example above.
