### ISSUE TITLE
bad gateway? 

### ISSUE THREAD

**Issue by biocyberman** [VictoriaMetrics/grafana-datasource#113]
Hi
I a prometheus+grafana user and want to give this a try. But the documentation is still not good enough. I still can't query anything from Grafana.

This is my `provisioning/datasources/victoriametrics.yml` file:

```
apiVersion: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
   # <string, required> Name of the VictoriaMetrics datasource 
   # displayed in Grafana panels and queries.
   - name: VictoriaMetrics
      # <string, required> Sets the data source type.
     type: victoriametrics-datasource
      # <string, required> Sets the access mode, either
      # proxy or direct (Server or Browser in the UI).
      # Some data sources are incompatible with any setting
      # but proxy (Server).
     access: proxy
     # <string> Sets default URL of the single node version of VictoriaMetrics
     url: http://localhost:8428
     # <string> Sets the pre-selected datasource for new panels. 
     # You can set only one default data source per organization.
     isDefault: true

     # <string, required> Name of the VictoriaMetrics datasource 
     # displayed in Grafana panels and queries.
   - name: VictoriaMetrics - cluster
     # <string, required> Sets the data source type.
     type: victoriametrics-datasource
     # <string, required> Sets the access mode, either
     # proxy or direct (Server or Browser in the UI).
     # Some data sources are incompatible with any setting
     # but proxy (Server).
     access: proxy
     # <string> Sets default URL of the cluster version of VictoriaMetrics
     url: http://localhost:8481/select/0/prometheus
     # <string> Sets the pre-selected datasource for new panels. 
     # You can set only one default data source per organization.
     isDefault: false
```

![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/447942/717d0b6f-c541-4830-a475-e14373faf0d1)

I went into Grafan Datasource and hit "Test" and got "bad gateway" error

![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/447942/c0518c10-2e5e-4833-be25-a6ec8b523da4)
