### ISSUE TITLE
vm-datasource not works, but prometheus data source works

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/grafana-datasource#127]
At fisrt, I create a config map like this:
```yaml
# datasource.yaml
apiVersion: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
    - name: Prometheus-realtime-cluster
      type: prometheus
      access: direct
      #orgId: 1
      url: http://10.43.113.112:8481/select/0/prometheus/
      #url: http://realtime-cluster-vm-select-service:8481/select/0/prometheus/
      isDefault: false
      version: 1
      editable: true

    - name: Prometheus-self-monitor-cluster
      type: prometheus
      access: direct
      #orgId: 1
      url: http://10.43.12.253:8481/self-monitor-cluster-select/select/0/prometheus/
      #url: http://self-monitor-cluster-vm-select-service:8481/self-monitor-cluster-select/select/0/prometheus/
      isDefault: false
      version: 1
      editable: true

    # <string, required> Name of the VictoriaMetrics datasource
    # displayed in Grafana panels and queries.
    - name: VictoriaMetrics-realtime-cluster
      # <string, required> Sets the data source type.
      type: victoriametrics-datasource
      # <string, required> Sets the access mode, either
      # proxy or direct (Server or Browser in the UI).
      # Some data sources are incompatible with any setting
      # but proxy (Server).
      access: direct
      # <string> Sets default URL of the single node version of VictoriaMetrics
      #url: http://realtime-cluster-vm-select-service:8481/select/0/prometheus/
      url: http://10.43.113.112:8481/select/0/prometheus/
      # <string> Sets the pre-selected datasource for new panels.
      # You can set only one default data source per organization.
      isDefault: false
      editable: true

    - name: VictoriaMetrics-self-monitor-cluster
      # <string, required> Sets the data source type.
      type: victoriametrics-datasource
      # <string, required> Sets the access mode, either
      # proxy or direct (Server or Browser in the UI).
      # Some data sources are incompatible with any setting
      # but proxy (Server).
      access: direct
      # <string> Sets default URL of the single node version of VictoriaMetrics
      #url: http://self-monitor-cluster-vm-select-service:8481/self-monitor-cluster-select/select/0/prometheus/
      url: http://10.43.12.253:8481/self-monitor-cluster-select/select/0/prometheus/
      # <string> Sets the pre-selected datasource for new panels.
      # You can set only one default data source per organization.
      isDefault: false
      editable: true
```

When I open grafana:
![0DA5A9F3-E243-4651-AEF5-81B8488AC01E](https://github.com/VictoriaMetrics/grafana-datasource/assets/4198375/4243c3fe-b6f3-4463-b86a-6c0184edee72)

vm-datasource can not connect. But prometheus datasource works.
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/4198375/b9f2bbe2-e4a8-4626-b4c5-6fdd2b806026)

And I create a new vm-datasource with same address, it works again.

So I think there might be some problem with yaml configed vm-data-source.

**Comment by dmitryk-dk** [comment]
Hi @ahfuzhang ! Can you try to test it with this PR
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5363

**Comment by ahfuzhang** [comment]
I don't understand.
I use k8s env, not docker compose.

**Comment by dmitryk-dk** [comment]
> I don't understand. I use k8s env, not docker compose.

Hi! Can you share how you run your k8s? Is there vmauth present?

**Comment by ahfuzhang** [comment]
my deploy code is here:
https://github.com/ahfuzhang/deploy_VictoriaMetrics_cluster/blob/main/terraform/realtime_cluster/grafana.tf

**Comment by dmitryk-dk** [comment]
> my deploy code is here: https://github.com/ahfuzhang/deploy_VictoriaMetrics_cluster/blob/main/terraform/realtime_cluster/grafana.tf

Can you share kubernetes manifests for the grafana which used for deploy (deployment, configmap)?

**Comment by ahfuzhang** [comment]
k8s deployment yaml:

```yaml
Name:                   realtime-cluster-grafana
Namespace:              test-devops
CreationTimestamp:      Tue, 02 Jan 2024 09:23:24 +0800
Labels:                 kubernetes_deployment_name=realtime-cluster-grafana
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               kubernetes_deployment_name=realtime-cluster-grafana
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  kubernetes_deployment_name=realtime-cluster-grafana
  Init Containers:
   realtime-cluster-grafana-init:
    Image:      alpine:3.18.4
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
    Args:
      -x
      /grafana/config/init.sh
    Environment:  <none>
    Mounts:
      /grafana/config/ from grafana-config-volume (rw)
      /vm-data/ from realtime-cluster-pvc (rw)
  Containers:
   realtime-cluster-grafana:
    Image:      grafana/grafana:10.2.2
    Port:       3000/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      CONTAINER_NAME:          (v1:metadata.name)
      CONTAINER_IP:            (v1:status.podIP)
      GOMAXPROCS:             1
      GF_PATHS_DATA:          /vm-data/grafana/data/
      GF_PATHS_PLUGINS:       /vm-data/grafana/plugins/
      GF_PATHS_PROVISIONING:  /vm-data/grafana/provisioning/
      GF_PATHS_CONFIG:        /vm-data/grafana/config/grafana.ini
    Mounts:
      /vm-data/ from realtime-cluster-pvc (rw)
  Volumes:
   realtime-cluster-pvc:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  realtime-cluster-pvc
    ReadOnly:   false
   grafana-config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      realtime-cluster-grafana-config
    Optional:  false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   realtime-cluster-grafana-7976c8b455 (1/1 replicas created)
Events:          <none>


```

config map yaml:

```yaml
Name:         realtime-cluster-grafana-config
Namespace:    test-devops
Labels:       <none>
Annotations:  <none>

Data
====
init.sh:
----
if [ ! -d "/vm-data/grafana/plugins/victoriametrics-datasource/" ]; then
    wget https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v0.5.0/victoriametrics-datasource-v0.5.0.tar.gz
    mkdir -p /vm-data/grafana/plugins/
    tar -zxf victoriametrics-datasource-v0.5.0.tar.gz -C /vm-data/grafana/plugins/
fi
mkdir -p /vm-data/grafana/provisioning/datasources/ /vm-data/grafana/config/ /vm-data/grafana/data/ /vm-data/grafana/plugins/
cp /grafana/config/datasource.yaml /vm-data/grafana/provisioning/datasources/
cp /grafana/config/grafana.ini /vm-data/grafana/config/
#echo "1" > /vm-data/grafana/data/test.txt
chmod -R 777 /vm-data/grafana/

#sleep 10


datasource.yaml:
----
apiVersion: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
    - name: Prometheus-realtime-cluster
      type: prometheus
      access: direct
      #orgId: 1
      url: http://10.43.113.112:8481/select/0/prometheus/
      #url: http://realtime-cluster-vm-select-service:8481/select/0/prometheus/
      isDefault: false
      version: 1
      editable: true

    - name: Prometheus-self-monitor-cluster
      type: prometheus
      access: direct
      #orgId: 1
      url: http://10.43.12.253:8481/self-monitor-cluster-select/select/0/prometheus/
      #url: http://self-monitor-cluster-vm-select-service:8481/self-monitor-cluster-select/select/0/prometheus/
      isDefault: false
      version: 1
      editable: true

    # <string, required> Name of the VictoriaMetrics datasource
    # displayed in Grafana panels and queries.
    - name: VictoriaMetrics-realtime-cluster
      # <string, required> Sets the data source type.
      type: victoriametrics-datasource
      # <string, required> Sets the access mode, either
      # proxy or direct (Server or Browser in the UI).
      # Some data sources are incompatible with any setting
      # but proxy (Server).
      access: direct
      # <string> Sets default URL of the single node version of VictoriaMetrics
      #url: http://realtime-cluster-vm-select-service:8481/select/0/prometheus/
      url: http://10.43.113.112:8481/select/0/prometheus/
      # <string> Sets the pre-selected datasource for new panels.
      # You can set only one default data source per organization.
      isDefault: false
      editable: true

    - name: VictoriaMetrics-self-monitor-cluster
      # <string, required> Sets the data source type.
      type: victoriametrics-datasource
      # <string, required> Sets the access mode, either
      # proxy or direct (Server or Browser in the UI).
      # Some data sources are incompatible with any setting
      # but proxy (Server).
      access: direct
      # <string> Sets default URL of the single node version of VictoriaMetrics
      #url: http://self-monitor-cluster-vm-select-service:8481/self-monitor-cluster-select/select/0/prometheus/
      url: http://10.43.12.253:8481/self-monitor-cluster-select/select/0/prometheus/
      # <string> Sets the pre-selected datasource for new panels.
      # You can set only one default data source per organization.
      isDefault: false
      editable: true


grafana.ini:
----
[plugins[]
allow_loading_unsigned_plugins = victoriametrics-datasource


BinaryData
====

Events:  <none>

```
