### ISSUE TITLE
Update install documentation for the plugin

### ISSUE THREAD

**Issue by SQLJames** [VictoriaMetrics/grafana-datasource#163]
The install documentation in the readme doesn't seem to include documentation around installing the plugin as a zip file directly from the releases site in this GitHub repository. 

When going through the documentation setting up the chart for my home lab, I needed to install Grafana separately prior to coming across VictoriaMetrics. So I didn't want to use the k8s-stack chart, however as noted in the [VictoriaMetrics k8s-stack chart](https://github.com/VictoriaMetrics/helm-charts/blob/bdbeb66a19d7c3c6426bb56b287511d54d06d1e4/charts/victoria-metrics-k8s-stack/values.yaml#L692) you can install the plugin easily without needing to run the extraInitContainers

```
grafana.ini:
  plugins:
    allow_loading_unsigned_plugins: victoriametrics-datasource
plugins:
  - https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v0.8.2/victoriametrics-datasource-v0.8.2.zip;victoriametrics-datasource
```

I am fine with making this change to the readme, however, prior to updating documentation or readme files I wanted to run it by maintainers. :)
