### ISSUE TITLE
provisioning the plugin

### ISSUE THREAD

**Issue by chouzee** [VictoriaMetrics/grafana-datasource#60]
Good evening! I have installed the plugin successfully, but not sure how to provision it correctly. previously, I was able to provision datasource using:
`  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true`
but it isn't configure the plugin and add another datasource. What I need to do to make the plugin works is to manually configure datasource in the plugin section and add the url, but then I got 2 datasources. Could you clarify what do I do wrong here, please?
![image](https://user-images.githubusercontent.com/8557950/225722902-199c7788-9194-4de1-b7ae-da967f9cda6f.png)

**Comment by chouzee** [comment]
I've tried to change the type to VictoriaMetrics as in the plugin, but it didn't help 
![image](https://user-images.githubusercontent.com/8557950/225723357-ac6db164-21d8-4c42-822e-633daa225bd2.png)

**Comment by dmitryk-dk** [comment]
Hi @chouzee ! When you install the plugin successfully, you should 
1: Go to the configuration section and click on the plugin
<img width="291" alt="Screenshot 2023-03-17 at 11 54 29" src="https://user-images.githubusercontent.com/12189570/225873544-360787f1-9123-431b-8501-4fa9040af11e.png">

2. Search `VictoriaMetrics` plugin as in the picture below
<img width="721" alt="Screenshot 2023-03-17 at 11 54 46" src="https://user-images.githubusercontent.com/12189570/225873701-8e395034-027f-4e19-a6e9-1501e0640f43.png">

3. Choose `VictoriaMetrics` plugin by clicking on it
4. Click on `Create VictoriaMetrics as datasource`
<img width="680" alt="Screenshot 2023-03-17 at 11 54 59" src="https://user-images.githubusercontent.com/12189570/225873888-da422517-94ed-47be-bca3-5dfd61624a58.png">

5. In the new window, you should see the data source configuration where you can specify the data source URL and save it:

<img width="697" alt="Screenshot 2023-03-17 at 11 59 38" src="https://user-images.githubusercontent.com/12189570/225874284-faae5caf-04c0-4349-ab10-7c35e2edb710.png">

I hope this will help you!

**Comment by chouzee** [comment]
Got it! I just though that I can do the same as in https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/provisioning/datasources/datasource.yml using Prometheus plugin.

**Comment by dmitryk-dk** [comment]
Hi @chouzee ! Checked your question, try to use this yaml file
```yaml
apiVersion: 1

datasources:
    - name: VictoriaMetrics
      type: victoriametrics-datasource
      access: proxy
      url: http://victoriametrics:8428
      isDefault: true

    - name: VictoriaMetrics - cluster
      type: victoriametrics-datasource
      access: proxy
      url: http://vmselect:8481/select/0/prometheus
      isDefault: false
```
And you should see       
<img width="1501" alt="Screenshot 2023-03-17 at 21 23 36" src="https://user-images.githubusercontent.com/12189570/226000335-ae101ed7-a40f-4dcc-bd0a-a2709d42a90a.png">
