### ISSUE TITLE
How to set "Link on vmui" declaratively?

### ISSUE THREAD

**Issue by holmesb** [VictoriaMetrics/grafana-datasource#83]
Hi,

@Loori-R recently [added ](https://github.com/VictoriaMetrics/grafana-datasource/pull/71)the ability to configure the link to vmui:

![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/5072156/836a75f9-6a0b-4a8e-9119-2be03a6f2f99)

Is it possible to configure this declaratively in Grafana's datasources.yaml? We configure everything using helm.

Many thanks

**Comment by Loori-R** [comment]
Hi, @holmesb.

Yes, you should define this configuration, something like this:

```
 datasources:
      - name: VictoriaMetrics
        type: victoriametrics-datasource
        url: http://victoriametrics:8428
        access: proxy
        isDefault: true
        jsonData:
          vmuiUrl: http://vmui
```
